export const db = "6a2bbffd00190eccf0b8"
export const questionCollection = "questions"
export const answerCollection = "answers"
export const commentCollection = "comments"
export const voteCollection = "votes"
export const questionAttachmentBucket = "6a2c69730007121e8fdb"